package generator

import (
	"bytes"
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/alanm/terraform-provider-typesense/internal/client"
	"github.com/alanm/terraform-provider-typesense/internal/tfnames"
	"github.com/alanm/terraform-provider-typesense/internal/version"
	"github.com/hashicorp/hcl/v2/hclwrite"
)

// Config holds the configuration for the generator
type Config struct {
	// Server connection
	Host     string
	Port     int
	Protocol string
	APIKey   string

	// Cloud connection
	CloudAPIKey string

	// Output settings
	OutputDir  string
	SingleFile bool

	// Data export settings
	IncludeData bool
}

// Generator handles the Terraform configuration generation
type Generator struct {
	config         *Config
	serverClient   *client.ServerClient
	cloudClient    *client.CloudClient
	serverVersion  *version.Version
	featureChecker version.FeatureChecker
}

// New creates a new Generator with the given configuration
func New(cfg *Config) *Generator {
	g := &Generator{
		config:         cfg,
		featureChecker: version.NewFallbackFeatureChecker(),
	}

	if cfg.Host != "" && cfg.APIKey != "" {
		g.serverClient = client.NewServerClient(cfg.Host, cfg.APIKey, cfg.Port, cfg.Protocol)
	}

	if cfg.CloudAPIKey != "" {
		g.cloudClient = client.NewCloudClient(cfg.CloudAPIKey)
	}

	return g
}

// DetectServerVersion queries the server and detects the version for feature-aware API selection.
// This should be called before Generate() for optimal API selection.
// On failure, it logs a warning and the generator will fall back to runtime detection.
func (g *Generator) DetectServerVersion(ctx context.Context) error {
	if g.serverClient == nil {
		return nil
	}

	info, err := g.serverClient.GetServerInfo(ctx)
	if err != nil {
		// Continue with fallback behavior
		fmt.Fprintf(os.Stderr, "Warning: Could not detect Typesense server version: %v\n", err)
		return nil
	}

	serverVersion, err := version.Parse(info.Version)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: Could not parse Typesense server version %q: %v\n", info.Version, err)
		return nil
	}

	g.serverVersion = serverVersion
	g.featureChecker = version.NewFeatureChecker(serverVersion)
	return nil
}

// fileSet manages multiple HCL output files, collapsing to a single file when SingleFile mode is enabled.
type fileSet struct {
	files      map[string]*hclwrite.File
	singleFile bool
}

func newFileSet(singleFile bool) *fileSet {
	return &fileSet{
		files:      make(map[string]*hclwrite.File),
		singleFile: singleFile,
	}
}

// get returns the HCL file for the given name, creating it if needed.
// In single-file mode, all names map to "main.tf".
func (fs *fileSet) get(name string) *hclwrite.File {
	if fs.singleFile {
		name = "main.tf"
	}
	if f, ok := fs.files[name]; ok {
		return f
	}
	f := hclwrite.NewEmptyFile()
	fs.files[name] = f
	return f
}

// Generate reads all resources and generates Terraform configuration
func (g *Generator) Generate(ctx context.Context) error {
	// Ensure output directory exists
	if err := os.MkdirAll(g.config.OutputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	fs := newFileSet(g.config.SingleFile)

	// Main file: header comment + terraform block + provider block
	mainFile := fs.get("main.tf")

	headerComment := fmt.Sprintf("# Generated by terraform-provider-typesense generate\n# Source: %s://%s:%d\n# Generated at: %s\n\n",
		g.config.Protocol, g.config.Host, g.config.Port, time.Now().UTC().Format(time.RFC3339))
	mainFile.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte(headerComment)},
	})

	generateTerraformBlock(mainFile)
	generateProviderBlock(mainFile, g.config.Host, g.config.Port, g.config.Protocol, g.serverClient != nil, g.cloudClient != nil)

	// Track resource names for uniqueness
	resourceNames := make(map[string]bool)
	collectionResourceMap := make(map[string]string) // collection name -> resource name

	// Collect import commands
	var importCommands []ImportCommand

	// Generate cloud clusters if cloud client is available
	if g.cloudClient != nil {
		if err := g.generateClusters(ctx, fs.get("cluster.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate clusters: %w", err)
		}
	}

	// Generate server resources if server client is available
	if g.serverClient != nil {
		if err := g.generateCollections(ctx, fs.get("collections.tf"), resourceNames, collectionResourceMap, &importCommands); err != nil {
			return fmt.Errorf("failed to generate collections: %w", err)
		}

		if err := g.generateCollectionAliases(ctx, fs.get("aliases.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate collection aliases: %w", err)
		}

		if err := g.generateStopwords(ctx, fs.get("stopwords.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate stopwords: %w", err)
		}

		if err := g.generateStemmingDictionaries(ctx, fs.get("stemming.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate stemming dictionaries: %w", err)
		}

		if err := g.generateSynonyms(ctx, fs.get("synonyms.tf"), resourceNames, collectionResourceMap, &importCommands); err != nil {
			return fmt.Errorf("failed to generate synonyms: %w", err)
		}

		if err := g.generateOverrides(ctx, fs.get("overrides.tf"), resourceNames, collectionResourceMap, &importCommands); err != nil {
			return fmt.Errorf("failed to generate overrides: %w", err)
		}

		if err := g.generatePresets(ctx, fs.get("presets.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate presets: %w", err)
		}

		if err := g.generateAnalyticsRules(ctx, fs.get("analytics.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate analytics rules: %w", err)
		}

		if err := g.generateAPIKeys(ctx, fs.get("api_keys.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate API keys: %w", err)
		}

		if err := g.generateNLSearchModels(ctx, fs.get("nl_search_models.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate NL search models: %w", err)
		}

		if err := g.generateConversationModels(ctx, fs.get("conversation_models.tf"), resourceNames, &importCommands); err != nil {
			return fmt.Errorf("failed to generate conversation models: %w", err)
		}
	}

	// Write all non-empty files
	for name, f := range fs.files {
		content := f.Bytes()
		if name != "main.tf" && len(bytes.TrimSpace(content)) == 0 {
			continue
		}
		filePath := filepath.Join(g.config.OutputDir, name)
		if err := os.WriteFile(filePath, content, 0644); err != nil {
			return fmt.Errorf("failed to write %s: %w", name, err)
		}
	}

	// Write imports.tf with HCL import blocks (Terraform 1.5+)
	if len(importCommands) > 0 {
		importsPath := filepath.Join(g.config.OutputDir, "imports.tf")
		importFile := GenerateImportBlocks(importCommands)
		if err := os.WriteFile(importsPath, importFile.Bytes(), 0644); err != nil {
			return fmt.Errorf("failed to write imports.tf: %w", err)
		}
	}

	return nil
}

// clusterMatchesHost checks if a cluster's hostnames match the given server host.
func clusterMatchesHost(cluster *client.Cluster, host string) bool {
	normalizedHost := normalizeHostname(host)
	for _, candidate := range clusterHostnames(cluster) {
		if normalizeHostname(candidate) == normalizedHost {
			return true
		}
	}
	return false
}

func normalizeHostname(host string) string {
	host = strings.TrimSpace(strings.ToLower(host))
	host = strings.TrimSuffix(host, ".")
	host = strings.TrimPrefix(host, "https://")
	host = strings.TrimPrefix(host, "http://")

	if parsedHost, _, err := net.SplitHostPort(host); err == nil {
		host = parsedHost
	}

	return host
}

func clusterHostnames(cluster *client.Cluster) []string {
	seen := make(map[string]bool)
	hostnames := make([]string, 0, len(cluster.Hostnames.Nodes)+2)

	appendIfNew := func(host string) {
		normalized := normalizeHostname(host)
		if normalized == "" || seen[normalized] {
			return
		}
		seen[normalized] = true
		hostnames = append(hostnames, host)
	}

	appendIfNew(cluster.Hostnames.SearchDeliveryNetwork)
	appendIfNew(cluster.Hostnames.LoadBalanced)
	for _, node := range cluster.Hostnames.Nodes {
		appendIfNew(node)
	}

	return hostnames
}

func clusterHostnameSummary(cluster *client.Cluster) string {
	label := cluster.Name
	if label == "" {
		label = "<unnamed>"
	}
	if cluster.ID != "" {
		label = fmt.Sprintf("%s (%s)", label, cluster.ID)
	}

	searchDeliveryNetwork := "<empty>"
	if cluster.Hostnames.SearchDeliveryNetwork != "" {
		searchDeliveryNetwork = strconv.Quote(cluster.Hostnames.SearchDeliveryNetwork)
	}

	loadBalanced := "<empty>"
	if cluster.Hostnames.LoadBalanced != "" {
		loadBalanced = strconv.Quote(cluster.Hostnames.LoadBalanced)
	}

	nodes := "[]"
	if len(cluster.Hostnames.Nodes) > 0 {
		quotedNodes := make([]string, len(cluster.Hostnames.Nodes))
		for i, node := range cluster.Hostnames.Nodes {
			quotedNodes[i] = strconv.Quote(node)
		}
		nodes = "[" + strings.Join(quotedNodes, ", ") + "]"
	}

	return fmt.Sprintf("%s: search_delivery_network=%s, load_balanced=%s, nodes=%s", label, searchDeliveryNetwork, loadBalanced, nodes)
}

func clusterHostnameInventory(clusters []client.Cluster) string {
	if len(clusters) == 0 {
		return "<no clusters returned>"
	}

	summaries := make([]string, 0, len(clusters))
	for _, cluster := range clusters {
		summaries = append(summaries, clusterHostnameSummary(&cluster))
	}

	return strings.Join(summaries, "; ")
}

func collectionFingerprint(collections []client.Collection) string {
	names := make([]string, 0, len(collections))
	for _, collection := range collections {
		names = append(names, collection.Name)
	}
	sort.Strings(names)
	return strings.Join(names, "\x00")
}

type clusterProbeFunc func(ctx context.Context, host string) ([]client.Collection, error)

func findClustersByServerProbe(ctx context.Context, clusters []client.Cluster, expectedFingerprint string, probe clusterProbeFunc) ([]client.Cluster, map[string]string) {
	var matched []client.Cluster
	matchedHosts := make(map[string]string)

	for _, cluster := range clusters {
		for _, host := range clusterHostnames(&cluster) {
			collections, err := probe(ctx, host)
			if err != nil {
				continue
			}
			if collectionFingerprint(collections) == expectedFingerprint {
				matched = append(matched, cluster)
				matchedHosts[cluster.ID] = host
				break
			}
		}
	}

	return matched, matchedHosts
}

func (g *Generator) generateClusters(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	clusters, err := g.cloudClient.ListClusters(ctx)
	if err != nil {
		return err
	}

	// When a server host is configured, scope to the matching cluster only.
	// The list endpoint may not include hostnames, so fetch full details for each cluster.
	if g.config.Host != "" {
		var matched []client.Cluster
		matchedByProbe := false
		inspected := make([]client.Cluster, 0, len(clusters))
		for _, cluster := range clusters {
			// First try matching against list response hostnames
			if clusterMatchesHost(&cluster, g.config.Host) {
				matched = append(matched, cluster)
				inspected = append(inspected, cluster)
				continue
			}
			// Fetch full cluster details to get hostnames
			full, err := g.cloudClient.GetCluster(ctx, cluster.ID)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: Could not fetch details for cluster %s: %v\n", cluster.ID, err)
				inspected = append(inspected, cluster)
				continue
			}
			if full != nil {
				inspected = append(inspected, *full)
				if clusterMatchesHost(full, g.config.Host) {
					matched = append(matched, *full)
				}
				continue
			}
			inspected = append(inspected, cluster)
		}

		if len(matched) > 0 {
			clusters = matched
		} else {
			if g.serverClient != nil {
				sourceCollections, err := g.serverClient.ListCollections(ctx)
				if err != nil {
					fmt.Fprintf(os.Stderr, "Warning: Could not fingerprint source server for smarter cluster matching: %v\n", err)
				} else {
					probeMatches, matchedHosts := findClustersByServerProbe(ctx, inspected, collectionFingerprint(sourceCollections), func(ctx context.Context, host string) ([]client.Collection, error) {
						probeCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
						defer cancel()

						probeClient := client.NewServerClient(host, g.config.APIKey, g.config.Port, g.config.Protocol)
						return probeClient.ListCollections(probeCtx)
					})

					if len(probeMatches) == 1 {
						match := probeMatches[0]
						fmt.Fprintf(os.Stderr, "Info: Matched server host %q to cluster %q by probing cluster hostname %q with the server API key.\n", g.config.Host, match.Name, matchedHosts[match.ID])
						clusters = probeMatches
						matchedByProbe = true
					} else if len(probeMatches) > 1 {
						fmt.Fprintf(os.Stderr, "Warning: Smarter cluster matching found multiple candidates for server host %q. Exporting all clusters.\n", g.config.Host)
					}
				}
			}
		}

		if len(matched) == 0 && !matchedByProbe {
			fmt.Fprintf(os.Stderr, "Warning: Could not match server host %q to any cluster hostname. Exporting all clusters.\n", g.config.Host)
			fmt.Fprintf(os.Stderr, "Available cluster hostnames: %s\n", clusterHostnameInventory(inspected))
		}
	}

	if len(clusters) == 0 {
		return nil
	}

	// Add section header
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# CLUSTERS\n# ============================================\n\n")},
	})
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte(clusterSectionMutabilityComment)},
	})

	for _, cluster := range clusters {
		resourceName := MakeUniqueResourceName(cluster.Name, resourceNames)
		block := generateClusterBlock(&cluster, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceCluster),
			ResourceName: resourceName,
			ImportID:     ClusterImportID(cluster.ID),
		})
	}

	return nil
}

func (g *Generator) generateCollections(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, collectionResourceMap map[string]string, importCommands *[]ImportCommand) error {
	collections, err := g.serverClient.ListCollections(ctx)
	if err != nil {
		return err
	}

	if len(collections) == 0 {
		return nil
	}

	// Add section header
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# COLLECTIONS\n# ============================================\n\n")},
	})

	for _, collection := range collections {
		resourceName := MakeUniqueResourceName(collection.Name, resourceNames)
		collectionResourceMap[collection.Name] = resourceName

		block := generateCollectionBlock(&collection, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceCollection),
			ResourceName: resourceName,
			ImportID:     CollectionImportID(collection.Name),
		})

		// Export documents, synonyms, and overrides if data export is enabled
		if g.config.IncludeData {
			if err := g.exportDocuments(ctx, collection.Name); err != nil {
				return fmt.Errorf("failed to export documents for collection %s: %w", collection.Name, err)
			}

			// Export synonyms for this collection
			dataDir := filepath.Join(g.config.OutputDir, "data")
			if err := g.exportSynonyms(ctx, collection.Name, dataDir); err != nil {
				return fmt.Errorf("failed to export synonyms for collection %s: %w", collection.Name, err)
			}

			// Export overrides for this collection
			if err := g.exportOverrides(ctx, collection.Name, dataDir); err != nil {
				return fmt.Errorf("failed to export overrides for collection %s: %w", collection.Name, err)
			}
		}
	}

	return nil
}

func (g *Generator) generateCollectionAliases(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	aliases, err := g.serverClient.ListCollectionAliases(ctx)
	if err != nil {
		return err
	}

	if len(aliases) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# COLLECTION ALIASES\n# ============================================\n\n")},
	})

	for _, alias := range aliases {
		resourceName := MakeUniqueResourceName(alias.Name, resourceNames)
		block := generateCollectionAliasBlock(&alias, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceCollectionAlias),
			ResourceName: resourceName,
			ImportID:     CollectionAliasImportID(alias.Name),
		})
	}

	return nil
}

func (g *Generator) generateStopwords(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	stopwordsSets, err := g.serverClient.ListStopwordsSets(ctx)
	if err != nil {
		return err
	}

	// Export stopwords data if data export is enabled (even if empty, creates the file)
	if g.config.IncludeData && len(stopwordsSets) > 0 {
		dataDir := filepath.Join(g.config.OutputDir, "data")
		if err := g.exportStopwordsSets(ctx, dataDir); err != nil {
			return fmt.Errorf("failed to export stopwords sets: %w", err)
		}
	}

	if len(stopwordsSets) == 0 {
		return nil
	}

	// Add section header
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# STOPWORDS SETS\n# ============================================\n\n")},
	})

	for _, sw := range stopwordsSets {
		resourceName := MakeUniqueResourceName(sw.ID, resourceNames)
		block := generateStopwordsBlock(&sw, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceStopwordsSet),
			ResourceName: resourceName,
			ImportID:     StopwordsImportID(sw.ID),
		})
	}

	return nil
}

func (g *Generator) generateStemmingDictionaries(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	if g.serverVersion != nil && !g.featureChecker.SupportsFeature(version.FeatureStemmingDictionaries) {
		return nil
	}

	dictionaries, err := g.serverClient.ListStemmingDictionaries(ctx)
	if err != nil {
		// Stemming dictionaries are only available on newer Typesense versions.
		fmt.Fprintf(os.Stderr, "Warning: Could not list stemming dictionaries: %v\n", err)
		return nil
	}

	if len(dictionaries) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# STEMMING DICTIONARIES\n# ============================================\n\n")},
	})

	for _, dictionary := range dictionaries {
		resourceName := MakeUniqueResourceName(dictionary.ID, resourceNames)
		block := generateStemmingDictionaryBlock(&dictionary, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceStemmingDictionary),
			ResourceName: resourceName,
			ImportID:     StemmingDictionaryImportID(dictionary.ID),
		})
	}

	return nil
}

func (g *Generator) generateSynonyms(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, collectionResourceMap map[string]string, importCommands *[]ImportCommand) error {
	// Use version-aware API selection
	if g.featureChecker.SupportsFeature(version.FeatureSynonymSets) {
		return g.generateSynonymSetsV30(ctx, f, resourceNames, importCommands)
	}

	// For v29 and earlier, or when version detection failed (fallback)
	// Try per-collection synonyms first, fall back to synonym_sets if 404
	return g.generatePerCollectionSynonyms(ctx, f, resourceNames, collectionResourceMap, importCommands)
}

// generateSynonymSetsV30 handles synonym generation for Typesense v30.0+ using the /synonym_sets API
func (g *Generator) generateSynonymSetsV30(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	synonymSets, err := g.serverClient.ListSynonymSets(ctx)
	if err != nil {
		return fmt.Errorf("failed to list synonym sets: %w", err)
	}

	if len(synonymSets) == 0 {
		return nil
	}

	// Add section header with version info
	versionStr := ""
	if g.serverVersion != nil {
		versionStr = fmt.Sprintf(" (detected server: v%s)", g.serverVersion.String())
	}
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte(fmt.Sprintf("# ============================================\n# SYNONYM SETS (Typesense v30.0+)%s\n# Note: Synonym sets are now system-level, not per-collection\n# ============================================\n\n", versionStr))},
	})

	g.appendSynonymSetResources(f, synonymSets, resourceNames, importCommands)

	return nil
}

// generatePerCollectionSynonyms handles synonym generation for Typesense v29 and earlier
// using the /collections/{name}/synonyms API
func (g *Generator) generatePerCollectionSynonyms(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, collectionResourceMap map[string]string, importCommands *[]ImportCommand) error {
	var allSynonyms []struct {
		synonym        client.Synonym
		collectionName string
	}

	collections, err := g.serverClient.ListCollections(ctx)
	if err != nil {
		return err
	}

	for _, collection := range collections {
		synonyms, err := g.serverClient.ListSynonyms(ctx, collection.Name)
		if err != nil {
			return fmt.Errorf("failed to list synonyms for collection %s: %w", collection.Name, err)
		}

		// If we get an empty list and version detection failed, it might be a v30+ server
		// The ListSynonyms method already handles 404 gracefully
		for _, syn := range synonyms {
			allSynonyms = append(allSynonyms, struct {
				synonym        client.Synonym
				collectionName string
			}{syn, collection.Name})
		}
	}

	if len(allSynonyms) == 0 {
		// If version detection failed and we got no synonyms, try the v30 API as fallback
		if g.serverVersion == nil {
			return g.generateSynonymSetsV30Fallback(ctx, f, resourceNames, importCommands)
		}
		return nil
	}

	// Add section header with version info
	versionStr := ""
	if g.serverVersion != nil {
		versionStr = fmt.Sprintf(" (detected server: v%s)", g.serverVersion.String())
	}
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte(fmt.Sprintf("# ============================================\n# SYNONYMS%s\n# ============================================\n\n", versionStr))},
	})

	for _, item := range allSynonyms {
		collectionResourceName := collectionResourceMap[item.collectionName]
		resourceName := MakeUniqueResourceName(item.collectionName+"_"+item.synonym.ID, resourceNames)
		block := generateSynonymBlock(&item.synonym, collectionResourceName, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceSynonym),
			ResourceName: resourceName,
			ImportID:     SynonymImportID(item.collectionName, item.synonym.ID),
		})
	}

	return nil
}

// generateSynonymSetsV30Fallback tries the v30 API when version detection failed
// and per-collection synonyms returned nothing
func (g *Generator) generateSynonymSetsV30Fallback(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	synonymSets, err := g.serverClient.ListSynonymSets(ctx)
	if err != nil || synonymSets == nil || len(synonymSets) == 0 {
		// Either failed or no synonym sets - that's fine
		return nil
	}

	// Found synonym sets via fallback
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# SYNONYM SETS (Typesense v30.0+)\n# Note: Synonym sets are now system-level, not per-collection\n# ============================================\n\n")},
	})

	g.appendSynonymSetResources(f, synonymSets, resourceNames, importCommands)

	return nil
}

func (g *Generator) appendSynonymSetResources(f *hclwrite.File, synonymSets []client.SynonymSet, resourceNames map[string]bool, importCommands *[]ImportCommand) {
	for _, synSet := range synonymSets {
		for _, item := range synSet.Synonyms {
			synonym := &client.Synonym{
				ID:       item.ID,
				Root:     item.Root,
				Synonyms: item.Synonyms,
			}
			resourceName := MakeUniqueResourceName(synSet.Name+"_"+item.ID, resourceNames)
			block := generateSynonymBlockWithCollectionLiteral(synonym, synSet.Name, resourceName)
			f.Body().AppendBlock(block)
			f.Body().AppendNewline()

			*importCommands = append(*importCommands, ImportCommand{
				ResourceType: tfnames.FullTypeName(tfnames.ResourceSynonym),
				ResourceName: resourceName,
				ImportID:     SynonymImportID(synSet.Name, item.ID),
			})
		}
	}
}

func (g *Generator) generateOverrides(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, collectionResourceMap map[string]string, importCommands *[]ImportCommand) error {
	// Use version-aware API selection
	if g.featureChecker.SupportsFeature(version.FeatureCurationSets) {
		return g.generateCurationSetsV30(ctx, f, resourceNames, importCommands)
	}

	// For v29 and earlier, or when version detection failed (fallback)
	return g.generatePerCollectionOverrides(ctx, f, resourceNames, collectionResourceMap, importCommands)
}

// generateCurationSetsV30 handles override generation for Typesense v30.0+ using the /curation_sets API
func (g *Generator) generateCurationSetsV30(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	curationSets, err := g.serverClient.ListCurationSets(ctx)
	if err != nil {
		return fmt.Errorf("failed to list curation sets: %w", err)
	}

	if len(curationSets) == 0 {
		return nil
	}

	// Add section header with version info
	versionStr := ""
	if g.serverVersion != nil {
		versionStr = fmt.Sprintf(" (detected server: v%s)", g.serverVersion.String())
	}
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte(fmt.Sprintf("# ============================================\n# CURATION SETS (Typesense v30.0+)%s\n# Note: Curation sets (formerly overrides) are now system-level, not per-collection\n# ============================================\n\n", versionStr))},
	})

	g.appendCurationSetResources(f, curationSets, resourceNames, importCommands)

	return nil
}

// generatePerCollectionOverrides handles override generation for Typesense v29 and earlier
// using the /collections/{name}/overrides API
func (g *Generator) generatePerCollectionOverrides(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, collectionResourceMap map[string]string, importCommands *[]ImportCommand) error {
	var allOverrides []struct {
		override       client.Override
		collectionName string
	}

	collections, err := g.serverClient.ListCollections(ctx)
	if err != nil {
		return err
	}

	for _, collection := range collections {
		overrides, err := g.serverClient.ListOverrides(ctx, collection.Name)
		if err != nil {
			return fmt.Errorf("failed to list overrides for collection %s: %w", collection.Name, err)
		}

		// If we get an empty list and version detection failed, it might be a v30+ server
		// The ListOverrides method already handles 404 gracefully
		for _, ovr := range overrides {
			allOverrides = append(allOverrides, struct {
				override       client.Override
				collectionName string
			}{ovr, collection.Name})
		}
	}

	if len(allOverrides) == 0 {
		// If version detection failed and we got no overrides, try the v30 API as fallback
		if g.serverVersion == nil {
			return g.generateCurationSetsV30Fallback(ctx, f, resourceNames, importCommands)
		}
		return nil
	}

	// Add section header with version info
	versionStr := ""
	if g.serverVersion != nil {
		versionStr = fmt.Sprintf(" (detected server: v%s)", g.serverVersion.String())
	}
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte(fmt.Sprintf("# ============================================\n# OVERRIDES%s\n# ============================================\n\n", versionStr))},
	})

	for _, item := range allOverrides {
		collectionResourceName := collectionResourceMap[item.collectionName]
		resourceName := MakeUniqueResourceName(item.collectionName+"_"+item.override.ID, resourceNames)
		block := generateOverrideBlock(&item.override, collectionResourceName, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceOverride),
			ResourceName: resourceName,
			ImportID:     OverrideImportID(item.collectionName, item.override.ID),
		})
	}

	return nil
}

// generateCurationSetsV30Fallback tries the v30 API when version detection failed
// and per-collection overrides returned nothing
func (g *Generator) generateCurationSetsV30Fallback(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	curationSets, err := g.serverClient.ListCurationSets(ctx)
	if err != nil || curationSets == nil || len(curationSets) == 0 {
		// Either failed or no curation sets - that's fine
		return nil
	}

	// Found curation sets via fallback
	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# CURATION SETS (Typesense v30.0+)\n# Note: Curation sets (formerly overrides) are now system-level, not per-collection\n# ============================================\n\n")},
	})

	g.appendCurationSetResources(f, curationSets, resourceNames, importCommands)

	return nil
}

func (g *Generator) generatePresets(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	presets, err := g.serverClient.ListPresets(ctx)
	if err != nil {
		return err
	}

	if len(presets) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# PRESETS\n# ============================================\n\n")},
	})

	for _, preset := range presets {
		resourceName := MakeUniqueResourceName(preset.Name, resourceNames)
		block := generatePresetBlock(&preset, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourcePreset),
			ResourceName: resourceName,
			ImportID:     PresetImportID(preset.Name),
		})
	}

	return nil
}

func (g *Generator) appendCurationSetResources(f *hclwrite.File, curationSets []client.CurationSet, resourceNames map[string]bool, importCommands *[]ImportCommand) {
	for _, curSet := range curationSets {
		for _, item := range curSet.Curations {
			override := curationItemToOverride(&item)
			resourceName := MakeUniqueResourceName(curSet.Name+"_"+item.ID, resourceNames)
			block := generateOverrideBlockWithCollectionLiteral(override, curSet.Name, resourceName)
			f.Body().AppendBlock(block)
			f.Body().AppendNewline()

			*importCommands = append(*importCommands, ImportCommand{
				ResourceType: tfnames.FullTypeName(tfnames.ResourceOverride),
				ResourceName: resourceName,
				ImportID:     OverrideImportID(curSet.Name, item.ID),
			})
		}
	}
}

func curationItemToOverride(c *client.CurationItem) *client.Override {
	return &client.Override{
		ID:                  c.ID,
		Rule:                c.Rule,
		Includes:            c.Includes,
		Excludes:            c.Excludes,
		FilterBy:            c.FilterBy,
		SortBy:              c.SortBy,
		ReplaceQuery:        c.ReplaceQuery,
		RemoveMatchedTokens: c.RemoveMatchedTokens,
		FilterCuratedHits:   c.FilterCuratedHits,
		EffectiveFromTs:     c.EffectiveFromTs,
		EffectiveToTs:       c.EffectiveToTs,
		StopProcessing:      c.StopProcessing,
	}
}

func (g *Generator) generateAnalyticsRules(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	rules, err := g.serverClient.ListAnalyticsRules(ctx)
	if err != nil {
		return err
	}

	if len(rules) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# ANALYTICS RULES\n# ============================================\n\n")},
	})

	for _, rule := range rules {
		resourceName := MakeUniqueResourceName(rule.Name, resourceNames)
		block := generateAnalyticsRuleBlock(&rule, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceAnalyticsRule),
			ResourceName: resourceName,
			ImportID:     AnalyticsRuleImportID(rule.Name),
		})
	}

	return nil
}

func (g *Generator) generateAPIKeys(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	keys, err := g.serverClient.ListAPIKeys(ctx)
	if err != nil {
		return err
	}

	if len(keys) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# API KEYS\n# ============================================\n\n")},
	})

	for _, key := range keys {
		name := key.Description
		if name == "" {
			name = fmt.Sprintf("key_%d", key.ID)
		}
		resourceName := MakeUniqueResourceName(name, resourceNames)
		block := generateAPIKeyBlock(&key, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceAPIKey),
			ResourceName: resourceName,
			ImportID:     APIKeyImportID(key.ID),
		})
	}

	return nil
}

func (g *Generator) generateNLSearchModels(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	models, err := g.serverClient.ListNLSearchModels(ctx)
	if err != nil {
		// NL search models may not be available on all server versions
		fmt.Fprintf(os.Stderr, "Warning: Could not list NL search models: %v\n", err)
		return nil
	}

	if len(models) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# NL SEARCH MODELS\n# Note: api_key must be set via var.openai_api_key\n# ============================================\n\n")},
	})

	for _, model := range models {
		resourceName := MakeUniqueResourceName(model.ID, resourceNames)
		block := generateNLSearchModelBlock(&model, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceNLSearchModel),
			ResourceName: resourceName,
			ImportID:     NLSearchModelImportID(model.ID),
		})
	}

	return nil
}

func (g *Generator) generateConversationModels(ctx context.Context, f *hclwrite.File, resourceNames map[string]bool, importCommands *[]ImportCommand) error {
	models, err := g.serverClient.ListConversationModels(ctx)
	if err != nil {
		// Conversation models may not be available on all server versions
		fmt.Fprintf(os.Stderr, "Warning: Could not list conversation models: %v\n", err)
		return nil
	}

	if len(models) == 0 {
		return nil
	}

	f.Body().AppendUnstructuredTokens(hclwrite.Tokens{
		{Type: 4, Bytes: []byte("# ============================================\n# CONVERSATION MODELS\n# Note: api_key must be set via var.openai_api_key\n# ============================================\n\n")},
	})

	for _, model := range models {
		resourceName := MakeUniqueResourceName(model.ID, resourceNames)
		block := generateConversationModelBlock(&model, resourceName)
		f.Body().AppendBlock(block)
		f.Body().AppendNewline()

		*importCommands = append(*importCommands, ImportCommand{
			ResourceType: tfnames.FullTypeName(tfnames.ResourceConversationModel),
			ResourceName: resourceName,
			ImportID:     ConversationModelImportID(model.ID),
		})
	}

	return nil
}
